### ISSUE TITLE
Error with more than 1 sheet of cards

### ISSUE THREAD

**Issue by CorvusVeis** [meduzik/deckbuilder#1]
If I have 1-sheet's worth of cards, then it always works. Below is how the cache looks.

![WorksWithOneSheet](https://user-images.githubusercontent.com/13970473/114746238-1f4dd280-9d15-11eb-9d79-a7ab52b98f1a.PNG)

If I have 2-sheet's worth of cards, then it throws an error. Below is the error and how the cache looks, since the error doesn't seem to like the cache.

![ErrorWithTwoSheets](https://user-images.githubusercontent.com/13970473/114746632-94b9a300-9d15-11eb-9cb6-95c5be2ca2fe.PNG)

![NotWorkWithTwoSheets](https://user-images.githubusercontent.com/13970473/114746662-a0a56500-9d15-11eb-982e-f406e4b57b63.PNG)

When testing and screenshotting, I delete the cache folder in-between attempts to load the card sheet in the browser. I also restart the deckbuilder server in-between attempts.

**Comment by meduzik** [comment]
Seems to be an issue with some file system deduplication. Changed the code to delete the target file prior to renaming.
